### ISSUE TITLE
Bir Lisans Ekleme

### ISSUE THREAD

**Issue by ercanersoy** [emirozturk/P2Otopark#1]
Merhabalar,

Bu depoda yer alan programa bir lisans eklemenizi öneririm. CoreBot reposundaki önceki bildimlerde tekrarlamamak için belirtmedim; programı açık kaynak yapacaksanız mutlaka bir açık kaynak lisans eklemelisiniz. Bütün hakları saklı bir programa lisans eklemenize gerek yoktur.

İlginiz için şimdiden teşekkür ederim.

**Comment by emirozturk** [comment]
Ekledim.
